package com.castellan.dao;

import com.castellan.pojo.Category;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Category record);

    /**
     * 检查父id是否存在
     * @param id
     * @return
     */
    int selectCategoryById(int id);

    /**
     * 添加一个类别
     * @param record
     * @return
     */
    int insertSelective(Category record);


    /**
     * update category
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * 检查类别是否已经存在(如果类别的名字和父节点相同则为同一类别)
     * @param categoryName
     * @param parentId
     * @return
     */
    int selectCategoryByParentIdAndName(@Param("categoryName") String categoryName, @Param("parentId") int parentId);

    List<Category> selectCategoryByParentId(int parentId);
}