package com.castellan.dao;

import com.castellan.pojo.Product;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);


    int updateByPrimaryKeySelective(Product record);

    List<Product> selectProductByNameAndProductId(@Param(value = "id") Integer id,@Param(value = "name") String name);

    List<Product> selectProductByKeywordAndCategoryId(@Param(value = "categoryId") Integer categoryId,@Param(value = "keyword") String keyword);

    List<Product> selectByNameAndCategoryIds(@Param(value = "keyword") String keyword,@Param("categoryIds") List<Integer> categoryIds);

    Integer selectStockByProductId(Integer id);
}